{{- if .Values.sedaiSync.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: sedai-kube-spec-controller-config
  namespace: {{ .Values.namespace }}
data:
  # This key becomes the filename inside the pod
  app-config.yaml: |
    logLevel: "{{ .Values.sedaiSync.logLevel }}"
{{- end }}