{{- if .Values.smartAgentEnroll.enabled }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.workload.smartAgentEnroll.name }}-post-upgrade-sa"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- with .Values.globalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.globalAnnotations }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "1"
    {{- toYaml .Values.globalAnnotations | nindent 4 }}
  {{- else }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "1"
  {{- end }}
{{- if and .Values.imagePullSecret.enabled .Values.imagePullSecret.secretName }}
imagePullSecrets:
  - name: "{{ .Values.imagePullSecret.secretName }}"
{{- end }}

{{- end }}