{{- if .Values.smartAgentEnroll.enabled }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Values.workload.smartAgentEnroll.name }}-post-upgrade-role"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- with .Values.globalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.globalAnnotations }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "1"
    {{- toYaml .Values.globalAnnotations | nindent 4 }}
  {{- else }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "1"
  {{- end }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "update", "delete"]

{{- end }}